# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"

    working_directory: /go/src/github.com/streetbyters/himage
    steps:
      - checkout
      - run: go mod tidy
      - run: go test -v -coverprofile=coverage.txt -covermode=atomic ./...
      - run: bash <(curl -s https://codecov.io/bash)